version: '3.8'

services:
  app:
    build: .
    container_name: php-app
    restart: always
    volumes:
      - .:/var/www/html
    expose:
      - "9000"

  nginx:
    image: nginx:latest
    container_name: nginx-server
    restart: always
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app