version: '3.8'

services:
  app:
    build: .
    container_name: issue-tracker-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
      - laravel_storage:/var/www/storage  # ✅ Persistent storage
    depends_on:
      - db
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=issue_tracker
      - DB_USERNAME=laravel
      - DB_PASSWORD=securepassword

  db:
    image: mysql:8.0
    container_name: issue-tracker-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: issue_tracker
      MYSQL_USER: laravel
      MYSQL_PASSWORD: securepassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  nginx:
    image: nginx:latest
    container_name: issue-tracker-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

volumes:
  db_data:
