---
- name: Setup EC2 Server with Docker, PHP, and MySQL
  hosts: all
  become: yes
  vars:
    db_root_password: "rootpassword"
    db_name: "issue_tracker"
    db_user: "laravel"
    db_password: "securepassword"

  tasks:
    # 1️⃣ Update and install dependencies
    - name: Update apt and install required packages
      apt:
        update_cache: yes
        name:
          - docker.io
          - docker-compose
          - unzip
          - php-cli
          - php-mbstring
          - php-xml
          - php-bcmath
          - php-tokenizer
          - php-curl
          - php-mysql
          - mysql-client
        state: present

    # 2️⃣ Start and enable Docker service
    - name: Start and enable Docker
      systemd:
        name: docker
        enabled: yes
        state: started

    # 3️⃣ Pull the MySQL Docker image and run it
    - name: Run MySQL container
      docker_container:
        name: mysql-db
        image: mysql:8.0
        state: started
        restart_policy: always
        ports:
          - "3306:3306"
        env:
          MYSQL_ROOT_PASSWORD: "{{ db_root_password }}"
          MYSQL_DATABASE: "{{ db_name }}"
          MYSQL_USER: "{{ db_user }}"
          MYSQL_PASSWORD: "{{ db_password }}"
        volumes:
          - mysql_data:/var/lib/mysql

    # 4️⃣ Pull PHP Docker image
    - name: Pull PHP Docker image
      docker_image:
        name: php:8.1-fpm
        source: pull

    # 5️⃣ Pull Nginx Docker image
    - name: Pull Nginx Docker image
      docker_image:
        name: nginx:latest
        source: pull