---
- name: Setup EC2 Server with Docker, PHP, and MySQL
  hosts: all
  become: yes
  vars:
    db_root_password: "rootpassword"
    db_name: "issue_tracker"
    db_user: "laravel"
    db_password: "securepassword"

  tasks:
    # 1️⃣ Update and Install Dependencies
    - name: Update apt and install required packages
      apt:
        update_cache: yes
        name:
          - docker.io
          - docker-compose
          - unzip
          - php-cli
          - php-fpm
          - php-mbstring
          - php-xml
          - php-bcmath
          - php-tokenizer
          - php-curl
          - php-mysql
          - mysql-client
          - nginx  # ✅ Ensure Nginx is installed
        state: present

    # 2️⃣ Start and Enable Docker Service
    - name: Start and enable Docker
      systemd:
        name: docker
        enabled: yes
        state: started

    # 3️⃣ Ensure MySQL Container is Running with Persistent Data
    - name: Run MySQL container
      docker_container:
        name: mysql-db
        image: mysql:8.0
        state: started
        restart_policy: always
        ports:
          - "3306:3306"
        env:
          MYSQL_ROOT_PASSWORD: "{{ db_root_password }}"
          MYSQL_DATABASE: "{{ db_name }}"
          MYSQL_USER: "{{ db_user }}"
          MYSQL_PASSWORD: "{{ db_password }}"
        volumes:
          - mysql_data:/var/lib/mysql
      register: mysql_container

    # 3.1️⃣ Ensure Docker Volume Exists for MySQL Data Persistence
    - name: Create persistent Docker volume for MySQL
      docker_volume:
        name: mysql_data
        state: present

    # 4️⃣ Ensure PHP-FPM is Installed (Dynamically Check Correct Version)
    - name: Install PHP-FPM
      apt:
        name: php-fpm
        state: present
      register: php_fpm_installed

    # 5️⃣ Get Correct PHP-FPM Version
    - name: Find installed PHP-FPM version
      shell: ls /etc/init.d/ | grep php
      register: php_fpm_version
      changed_when: false

    # 6️⃣ Start and Enable PHP-FPM Service
    - name: Start and enable PHP-FPM service
      systemd:
        name: "{{ php_fpm_version.stdout }}"
        enabled: yes
        state: started
      when: php_fpm_version.stdout | length > 0

    # 5️⃣ Ensure Nginx is Installed and Running
    - name: Start and enable Nginx service
      systemd:
        name: nginx
        enabled: yes
        state: started

    # 6️⃣ Pull PHP Docker Image (If Required)
    - name: Pull PHP Docker image
      docker_image:
        name: php:8.1-fpm
        source: pull

    # 7️⃣ Pull Nginx Docker Image (If Required)
    - name: Pull Nginx Docker image
      docker_image:
        name: nginx:latest
        source: pull