name: Deploy Laravel to EC2

on:
  workflow_dispatch:
    inputs:
      AWS_HOST:
        description: "EC2 Instance IP Address"
        required: true
      AWS_USER:
        description: "SSH Username (e.g., ubuntu, ec2-user)"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

- name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PRIVATE_KEY }}" | base64 -d > ~/.ssh/raktas.pem
          chmod 600 ~/.ssh/raktas.pem
          ssh-keyscan -H ${{ github.event.inputs.AWS_HOST }} > ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Run Ansible Playbook (Deploy Laravel)
        run: |
          ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i ${{ github.event.inputs.AWS_HOST }}, -u ${{ github.event.inputs.AWS_USER }} --private-key ~/.ssh/manoraktaskey.pem deploy_laravel.yml