name: Deploy Laravel to Docker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout Repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup SSH Key for Server Access
      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PRIVATE_KEY }}" | base64 --decode > ~/.ssh/raktas.pem
          chmod 600 ~/.ssh/iraktas.pem
          ssh-keyscan -H ${{ secrets.AWS_HOST }} >> ~/.ssh/known_hosts

      # 3️⃣ Deploy Laravel App via Ansible
      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i ${{ secrets.AWS_HOST }}, -u ubuntu --private-key ~/.ssh/raktas.pem deploy_laravel.yml
