name: Setup EC2 Server

on:
  workflow_dispatch:
    inputs:
      AWS_HOST:
        description: "EC2 Instance IP Address"
        required: true
      AWS_USER:
        description: "SSH Username (e.g., ubuntu, ec2-user)"
        required: true

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout Repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Install Ansible
      - name: Install Ansible
        run: |
          sudo apt update -y
          sudo apt install -y ansible

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/manoKey.pem
          chmod 600 ~/.ssh/manoKey.pem
          ssh-keyscan -H ${{ github.event.inputs.AWS_HOST }} >> ~/.ssh/known_hosts
      # - name: Setup SSH Key
      #   run: |
      #     mkdir -p ~/.ssh
      #     echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/manoKey.pem
      #     hmod 600 ~/.ssh/manoKey.pem
      #     ssh-keyscan -H ${{ github.event.inputs.AWS_HOST }} > ~/.ssh/known_hosts
      #     chmod 644 ~/.ssh/known_hosts

      # 4️⃣ Run Ansible Playbook (Setup Server)
      - name: Run Ansible Playbook (Setup Server)
        run: |
          ansible-playbook -i ${{ github.event.inputs.AWS_HOST }}, -u ${{ github.event.inputs.AWS_USER }} --private-key ~/.ssh/manoKey.pem setup_server.yml