name: Deploy AWS Infrastructure with Terraform

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout Repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup Terraform CLI
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7  # Adjust based on your Terraform version

      # 3️⃣ Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1  # Adjust region if needed

      # 4️⃣ Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # 5️⃣ Validate Terraform Configuration
      - name: Terraform Validate
        run: terraform validate

      # 6️⃣ Terraform Plan
      - name: Terraform Plan
        run: terraform plan

      # 7️⃣ Terraform Apply
      - name: Terraform Apply
        run: terraform apply -auto-approve